[package]
name = "day10"
version = "0.1.0"
authors = ["Jacob Lambert <jacob.lambert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1"
itertools = "0.8.2"